config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"
}

resources :users do
  collection do
    post 'login'
  end
end


  root "devices#index"
  resources :records do
    collection do
      get "api_endpoint"
    end
  end

  resources :devices do
    collection do
      get "refresh"
      get "api_endpoint"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/device.rb
class Device < ApplicationRecord
  validates :device_id, uniqueness: true

  def create_new_record
    nest = NestApi::Api.new

    api_device = nest.get_thermostat_by_name(self.name)

    record = Record.new

    
    record.device_id = api_device.get("device_id")
    record.humidity = api_device.get("humidity")
    record.internal_temp = api_device.get("ambient_temperature_f")

    record.time_to_target = api_device.get("time_to_target")
    record.name = api_device.get("name_long")
    
    if api_device.get("hvac_state").eql? "heating"
      record.target_temp = api_device.get("target_temperature_f")
    else
      record.target_temp = 0
    end
    
    forecast = ForecastIO.forecast(ENV['FORECAST_IO_LATITUDE'].to_f, ENV['FORECAST_IO_LONGITUDE'].to_f)
    # ap forecast
    record.external_temp = forecast["currently"]["temperature"]

    record.external_humidity = forecast["currently"]["humidity"] * 100

    record.save

  end
  #has_many :records
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all


    @devices.first.create_new_record
  end

  def api_endpoint
    devices = Device.all
    
    respond_to do |format|
      format.json {render json: devices}
    end
  end

  def refresh

    nest = NestApi::Api.new

    @remotedevices   =  nest.get_thermostat_list

    @remotedevices.each do |device|
      ap device
      data = device[1]
      device_name = data.get('device_id')
      puts device_name
      #ap Device.where(device_id: device_name)
      #unless Device.where(device_id: device_name).count > 0
      new_device = Device.create(device_id: data.get("device_id"),name: data.get("name"),
                                 name_long: data.get("name_long"),
                                 can_heat: data.get("can_heat"),
                                 can_cool: data.get("can_cool"))
      #end
    end

    redirect_to devices_path
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:device_id, :name, :name_long, :is_online, :can_cool, :can_heat, :last_connection)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.haml
= form_with(model: device, local: true) do |form|
  - if device.errors.any?
    #error_explanation
      %h2
        = pluralize(device.errors.count, "error")
        prohibited this device from being saved:
      %ul
        - device.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :device_id
    = form.text_field :device_id, id: :device_device_id
  .field
    = form.label :name
    = form.text_field :name, id: :device_name
  .field
    = form.label :name_long
    = form.text_field :name_long, id: :device_name_long
  .field
    = form.label :is_online
    = form.check_box :is_online, id: :device_is_online
  .field
    = form.label :can_cool
    = form.check_box :can_cool, id: :device_can_cool
  .field
    = form.label :can_heat
    = form.check_box :can_heat, id: :device_can_heat
  .field
    = form.label :last_connection
    = form.date_select :last_connection, id: :device_last_connection
  .actions
    = form.submit

app/views/devices/edit.html.haml
%h1 Editing Device
= render 'form', device: @device
= link_to 'Show', @device
|
= link_to 'Back', devices_path

app/views/devices/index.html.haml
%p#notice= notice
%h1 Devices
%table.table-bordered.table-hover{:style => "margin: 20px;"}
  %thead
    %tr
      %th Name
      %th Name long
      %th Can cool
      %th Can heat
      %th{:colspan => "3"}
  %tbody
    - @devices.each do |device|
      %tr
        %td= device.name
        %td= device.name_long
        %td= device.can_cool
        %td= device.can_heat
        %td= link_to 'Show', records_path(:device_id => device.device_id, :device_name => device.name_long)
        %td= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'Refresh Device List', refresh_devices_path

:css
  .table-bordered>tbody>tr>td, .table-bordered>tbody>tr>th, .table-bordered>tfoot>tr>td, .table-bordered>tfoot>tr>th, .table-bordered>thead>tr>td, .table-bordered>thead>tr>th {
    padding: 12px;
  }

app/views/devices/new.html.haml
%h1 New Device
= render 'form', device: @device
= link_to 'Back', devices_path

app/views/devices/show.html.haml
%p#notice= notice
%p
  %strong Device:
  = @device.device_id
%p
  %strong Name:
  = @device.name
%p
  %strong Name long:
  = @device.name_long
%p
  %strong Is online:
  = @device.is_online
%p
  %strong Can cool:
  = @device.can_cool
%p
  %strong Can heat:
  = @device.can_heat
%p
  %strong Last connection:
  = @device.last_connection
= link_to 'Edit', edit_device_path(@device)
|
= link_to 'Back', devices_path