config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"
}

resources :users do
  collection do
    post 'login'
  end
end


  root "devices#index"
  resources :records do
    collection do
      get "api_endpoint"
    end
  end

  resources :devices do
    collection do
      get "refresh"
      get "api_endpoint"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/record.rb
class Record < ApplicationRecord

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  require 'nest_api'
  require 'awesome_print' # gem install awesome_print
  require 'forecast_io'

  # GET /records
  # GET /records.json
  def index
    @device_id = params[:device_id]

    partial_records = Record.where(device_id: params[:device_id])
    
    if params[:filter].nil? || params[:filter].empty? || params[:filter] == "today"
      @records = partial_records.where("created_at >= ?", Time.zone.now - 24.hours)
      @selected_filter = "today"
    elsif params[:filter] == "yesterday"
      @selected_filter = "yesterday"
      @records = partial_records.where("created_at >= ? and created_at <= ?",
                                       Time.zone.yesterday.beginning_of_day,
                                       Time.zone.yesterday.end_of_day)
    elsif params[:filter] == "week"
      @selected_filter = "week"
      @records = partial_records.where("created_at >= ?", Time.zone.now - 7.days)
    elsif params[:filter] == "all"
      @selected_filter = "all"
      @records = partial_records
    elsif params[:filter] == "custom"
      @selected_filter = "custom"
      @records = partial_records.where("created_at >= ? and created_at <= ?",
                                       Time.zone.parse(params[:start]).beginning_of_day,
                                       Time.zone.parse(params[:end]).end_of_day)
      @start_date = params[:start]
      @end_date = params[:end]
    end

    @device_name = params[:device_name]
    if @device_name.nil?
      @device_name = Device.where(:device_id => @device_id).first.name_long
    end
    @max = [@records.maximum(:internal_temp), @records.maximum(:external_temp), @records.maximum(:humidity), @records.maximum(:external_humidity)].max
    @min = [@records.minimum(:internal_temp), @records.minimum(:external_temp), @records.minimum(:humidity), @records.minimum(:external_humidity)].min

    @data = [
      {name: "Internal Temperature", data: @records.group(:created_at).maximum(:internal_temp)},
      {name: "External Temperature", data: @records.group(:created_at).maximum(:external_temp)},
      {name: "Int. Humidity", data: @records.group(:created_at).maximum(:humidity)},
      {name: "Ext. Humidity", data: @records.group(:created_at).maximum(:external_humidity)},
      {name: "Time to Target", data: @records.group(:created_at).maximum(:time_to_target)},
      {name: "Heating to Temp", data: @records.group(:created_at).maximum(:target_temp)}
    ]

  end

  def api_endpoint

    @device_id = params[:device_id]

    partial_records = Record.where(device_id: params[:device_id]).where("created_at >= ? and created_at <= ?",
      Time.zone.parse(params[:start]).beginning_of_day,
      Time.zone.parse(params[:end]).end_of_day)

    respond_to do |format|
      format.json {render json: partial_records}
    end
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  def discover_thermostats
    nest = NestApi::Api.new
    nest.get_thermostat_list.last

    device =  nest.get_thermostat_list.first[1]
  end

  # GET /records/new
  def new
    @record = Record.new

    respond_to do |format|
      if @record.save
        format.html { redirect_to(records_path)}
      end
    end

    #@record.save!
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:internal_temp, :external_temp, :nest_temp, :nest_temp_high, :nest_temp_low)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.haml
= form_with(model: record, local: true) do |form|
  - if record.errors.any?
    #error_explanation
      %h2
        = pluralize(record.errors.count, "error")
        prohibited this record from being saved:
      %ul
        - record.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :internal_temp
    = form.text_field :internal_temp, id: :record_internal_temp
  .field
    = form.label :external_temp
    = form.text_field :external_temp, id: :record_external_temp
  .field
    = form.label :nest_temp
    = form.text_field :nest_temp, id: :record_nest_temp
  .field
    = form.label :nest_temp_high
    = form.text_field :nest_temp_high, id: :record_nest_temp_high
  .field
    = form.label :nest_temp_low
    = form.text_field :nest_temp_low, id: :record_nest_temp_low
  .actions
    = form.submit

app/views/records/edit.html.haml
%h1 Editing Record
= render 'form', record: @record
= link_to 'Show', @record
|
= link_to 'Back', records_path

app/views/records/index.html.haml
%p#notice= notice

= link_to '<div class="glyphicon glyphicon-chevron-left"></div> Back to devices'.html_safe,  devices_path

%h1
  = @device_name

- buttonclass = "btn btn-sm btn-primary"
- selectedclass = buttonclass + " active"
= link_to "Last 24 Hours", records_path(:filter => "today", :device_id => @device_id), :class => @selected_filter == "today" ? selectedclass : buttonclass
= link_to "Yesterday", records_path(:filter => "yesterday", :device_id => @device_id), :class => @selected_filter == "yesterday" ? selectedclass : buttonclass
= link_to "Running Week", records_path(:filter => "week", :device_id => @device_id), :class => @selected_filter == "week" ? selectedclass : buttonclass
= link_to "All", records_path(:filter => "all", :device_id => @device_id), :class => @selected_filter == "all" ? selectedclass : buttonclass
#custombtn{:class => @selected_filter == "custom" ? selectedclass : buttonclass}
  Custom

.custom_range{:style => "margin-top:10px;display:" + (@selected_filter == "custom" ? "inline" : "none")}
  = form_tag(records_path, :method => "get") do
    = text_field_tag :start, params[:start].nil? ? "Start Date" : params[:start],class: "datepickerstart"
    = text_field_tag :end, params[:end].nil? ? "End Date" : params[:end],class: "datepickerend"
    = hidden_field_tag :device_id, @device_id
    = hidden_field_tag :filter, "custom"
    = submit_tag "Apply", :class => buttonclass


%br/
= line_chart @data, min: @min, max:@max


:javascript
   $('.datepickerstart').pickadate({
    onSet: function(context) {
      console.log(context);
    }
  });

  $('.datepickerend').pickadate({
    onSet: function(context) {
      console.log(context);
    }
  });

  $("#custombtn").click(function(){
    if($(".custom_range").css('display') == "none")
    {
      $('.custom_range').show();
    }
    else
    {
      $('.custom_range').hide();
    }
  });

:css
  .table-padded>tbody>tr>td, .table-padded>tbody>tr>th, .table-padded>tfoot>tr>td, .table-padded>tfoot>tr>th, .table-padded>thead>tr>td, .table-padded>thead>tr>th {
    padding: 12px;
  }

  .button_to {
    float:left;
    margin: 0 8px 0 8px;
  }

app/views/records/new.html.haml
%h1 New Record
= render 'form', record: @record
= link_to 'Back', records_path

app/views/records/show.html.haml
%p#notice= notice
%p
  %strong Internal temp:
  = @record.internal_temp
%p
  %strong External temp:
  = @record.external_temp
%p
  %strong Nest temp:
  = @record.nest_temp
%p
  %strong Nest temp high:
  = @record.nest_temp_high
%p
  %strong Nest temp low:
  = @record.nest_temp_low
%p
  %strong Current Humidity:
  = @record.humidity
= link_to 'Edit', edit_record_path(@record)
|
= link_to 'Back', records_path